# Generated by Django 4.2.7 on 2023-11-30 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ')),
                ('group', models.CharField(choices=[('1', 'خرج'), ('2', 'درآمد')], max_length=1, null=True, verbose_name='نوع تراکنش')),
                ('date', models.DateField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
