# Generated by Django 4.2.7 on 2023-12-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_manager_name': 'objects', 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.CharField(choices=[('1', 'expense'), ('2', 'income')], max_length=1, null=True, verbose_name='نوع تراکنش'),
        ),
    ]
