version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver --settings=config.production_settings 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_USER: "${POSTGRES_USER}"

volumes:
  postgres_data: