version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4542
      - POSTGRES_DB=jeeb_man

volumes:
  postgres_data: