# Generated by Django 4.2.7 on 2023-12-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('1', 'expense'), ('2', 'income')], default='1', max_length=1, verbose_name='نوع دسته بندی'),
        ),
    ]
